import { useI18n } from './i18n.tsx';
const copy = {
  needsCovering: ['Needs covering', 'يحتاج تغطية'],
  allAssigned: ['Everything assigned', 'وُزّع المال بالكامل'],
  availableSpend: ['Available to spend', 'متاح للإنفاق'],
  availableHelp: ['In spending categories', 'في بنود الإنفاق'],
  spentMonth: ['Spent this month', 'إنفاق هذا الشهر'],
  netSpending: ['Net of refunds and corrections', 'بعد الاستردادات والتصحيحات'],
  reserves: ['Set aside', 'مال مخصص'],
  reservesHelp: ['Reserves and loan payments', 'الاحتياطيات ودفعات القروض'],
  savings: ['Savings goals', 'أهداف الادخار'],
  savingsHelp: ['Available in your goals', 'متاح في أهدافك'],
  spendingChart: ['Spending this month', 'الإنفاق هذا الشهر'],
  spendingHelp: ['Cumulative spending vs. an even pace for spending categories', 'الإنفاق التراكمي مقارنة بوتيرة متساوية لبنود الإنفاق'],
  actual: ['Actual', 'الفعلي'],
  plannedPace: ['Planned pace', 'الوتيرة المخططة'],
  allocation: ['Where your money is assigned', 'أين وُزّع مالك'],
  totalAssigned: ['Available in categories', 'متاح في البنود'],
  categoryProgress: ['Category progress', 'تقدم الفئات'],
  spentPlanned: ['Spent / planned', 'المُنفق / المخطط'],
  noSpending: ['No spending recorded this month yet.', 'لم يُسجّل إنفاق هذا الشهر بعد.'],
  noAllocation: ['Assign money to see your breakdown.', 'وزّع المال لعرض تفاصيله.'],
  noCategories: ['Create your plan to see category progress.', 'أنشئ خطتك لعرض تقدم الفئات.'],
  currencyPlan: ['Category progress is shown in your plan currency.', 'يُعرض تقدم الفئات بعملة الخطة.'],
  overspent: ['Over plan', 'تجاوز المخطط'],
  walletBalance: ['Cash balance', 'الرصيد النقدي'],
  viewWallets: ['View wallets', 'عرض المحافظ'],
  nextStep: ['Your next step', 'خطوتك التالية'],
  givePurpose: ['Give your money a purpose', 'امنح مالك غرضًا'],
  readyBody: ['Money you have, waiting to be put into your plan.', 'مال تملكه ينتظر توزيعه على خطتك.'],
  fund: ['Fund my plan', 'موّل خطتي'],
  viewPlan: ['View this month’s plan', 'عرض خطة هذا الشهر'],
  funded: ['Your money has a purpose', 'لمالك غرض الآن'],
  fundedBody: ['Your money is assigned. Open your plan to see what each item holds.', 'وُزّع مالك. افتح خطتك لمعرفة ما يحتويه كل بند.'],
  breakdown: ['Money breakdown', 'تفاصيل المال'],
  wallets: ['Your wallets', 'محافظك'],
  planDetails: ['Plan details', 'تفاصيل الخطة'],
  accountActions: ['Account actions', 'إجراءات الحساب'],
  search: ['Search loaded activity', 'البحث في النشاط المحمّل'],
  noSearch: ['No loaded records match. Load more to search older activity.', 'لا قيود محمّلة تطابق البحث. حمّل المزيد للبحث في النشاط الأقدم.'],
  moreFilters: ['More filters', 'فلاتر إضافية'],
  allTypes: ['All loaded types', 'كل الأنواع المحمّلة'],
  tourIntro: ['New here? See how your money works.', 'جديد هنا؟ تعرّف على طريقة عمل مالك.'],
  startTour: ['Start the tour', 'ابدأ الجولة'],
  restartTour: ['Restart guided tour', 'أعد الجولة الإرشادية'],
  skipTour: ['Skip tour', 'تخطَّ الجولة'],
  tourProgress: ['Guided tour', 'الجولة الإرشادية'],
  tourDone: ['Finish tour', 'إنهاء الجولة'],
  glossary: ['Money glossary', 'قاموس المال'],
  glossaryIntro: ['What these numbers mean', 'ما تعنيه هذه الأرقام'],
  help: ['Help', 'المساعدة'],
  referenceHelp: ['For combined views only. Wallet balances stay in their own currencies.', 'للعرض المجمّع فقط. تبقى أرصدة المحافظ بعملاتها.'],
} as const;
export function useUiCopy() {
  const { locale } = useI18n();
  return (key: keyof typeof copy): string => copy[key][locale === 'ar' ? 1 : 0];
}
