import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import { test, expect } from '@playwright/test';
import { createBudgetApi } from '../src/api/budget-api.ts';
import { translate } from '../src/lib/i18n.tsx';
import { localStackUp, signIn, storyUser } from './support.ts';

test.beforeAll(async () => { if (!(await localStackUp())) throw new Error('Start the local preview stack first.'); });
for (const locale of ['en', 'ar'] as const) {
  test(`partial bills and move/detach preserve money in ${locale}`, async ({ page }) => {
    const user = await storyUser();
    const env = readFileSync('.env.demo.local', 'utf8');
    const value = (key: string) => new RegExp(`^${key}=(.*)$`, 'm').exec(env)?.[1]?.trim() ?? '';
    const url = value('VITE_SUPABASE_URL');
    if (!/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(url)) throw new Error('Local DB only');
    const client = createClient(url, value('VITE_SUPABASE_ANON_KEY'), { auth: { persistSession: false, autoRefreshToken: false } });
    await client.auth.signInWithPassword(user);
    const api = createBudgetApi(client);
    const space = (await api.mySpaces())[0]!;
    const plan = await api.planMonth(space.id, space.currentMonth);
    const item = plan.groups.flatMap((group) => group.items).find((item) => item.nameEn === 'Bills')!;
    const wallet = (await api.accounts(space.id)).wallets.find((wallet) => wallet.kind === 'cash' && wallet.currency === 'USD')!;
    const cmd = () => ({ spaceId: space.id, requestId: randomUUID() });
    const source = await api.saveBill({ ...cmd(), name: 'Audit bill source', itemId: item.itemId, amount: 6000n, currency: 'USD', cadence: 'once', firstDue: space.today });
    const target = await api.saveBill({ ...cmd(), name: 'Audit bill target', itemId: item.itemId, amount: 6000n, currency: 'USD', cadence: 'once', firstDue: space.today });
    const payment = await api.recordExpense({ ...cmd(), walletId: wallet.id, itemId: item.itemId, amount: 2000n, on: space.today, billId: source.billId, billDue: space.today, memo: 'Audit partial payment' });
    const t = (key: Parameters<typeof translate>[1]) => translate(locale, key);
    await signIn(page, user);
    await expect(page.getByRole('region', { name: 'Your money', exact: true })).toBeVisible();
    await page.evaluate((locale) => localStorage.setItem('budget:locale', locale), locale);
    await page.reload();
    const row = page.getByRole('listitem').filter({ has: page.getByText('Audit bill source', { exact: true }) });
    await expect(row).toContainText(t('bill.status.partial'));
    await expect(row.locator('bdi.cr-amount[dir="ltr"]').first()).toBeVisible();
    await row.getByRole('button', { name: t('bill.pay'), exact: true }).click();
    const dialog = page.getByRole('dialog');
    await expect(dialog.getByLabel(t('common.amount'))).toHaveValue('40');
    await dialog.getByRole('button', { name: t('record.saveExpense'), exact: true }).click();
    await dialog.getByRole('button', { name: t('common.done'), exact: true }).click();
    const occurrences = () => api.billsUpcoming(space.id, space.today, space.today);
    expect((await occurrences()).find((bill) => bill.billId === source.billId)).toMatchObject({ status: 'paid', paidAmount: 6000n, paymentCount: 2 });
    const before = await api.accounts(space.id);
    await page.goto('/#/activity');
    const entryRow = page.getByRole('listitem').filter({ hasText: 'Audit bill source' }).filter({ has: page.locator('bdi.cr-amount', { hasText: locale === 'en' ? '20.00' : '٢٠٫٠٠' }) });
    await entryRow.getByRole('button').click();
    await dialog.getByRole('button', { name: t('bill.movePayment'), exact: true }).click();
    await dialog.getByLabel(t('bill.target'), { exact: true }).selectOption(target.billId);
    await dialog.getByRole('button', { name: t('bill.movePayment'), exact: true }).click();
    await expect(dialog).toHaveCount(0);
    expect(await api.accounts(space.id)).toEqual(before);
    expect((await occurrences()).find((bill) => bill.billId === source.billId)).toMatchObject({ status: 'part_paid', remaining: 2000n });
    expect((await occurrences()).find((bill) => bill.billId === target.billId)).toMatchObject({ status: 'part_paid', paidAmount: 2000n });
    await page.getByRole('listitem').filter({ hasText: 'Audit bill target' }).getByRole('button').click();
    await expect(dialog.getByRole('region', { name: t('bill.linkHistory') })).toContainText('Audit bill target');
    await dialog.getByRole('button', { name: t('bill.movePayment'), exact: true }).click();
    await dialog.getByRole('button', { name: t('bill.detachPayment'), exact: true }).click();
    await expect(dialog).toHaveCount(0);
    expect(await api.accounts(space.id)).toEqual(before);
    expect((await occurrences()).find((bill) => bill.billId === target.billId)).toMatchObject({ paidAmount: 0n, remaining: 6000n });
    const entry = (await api.activity(space.id)).entries.find((entry) => entry.entryId === payment.entryId)!;
    expect(entry).toMatchObject({ billId: null, billLinkVersion: 2 });
    expect(entry.billLinkHistory).toHaveLength(2);
    await page.getByRole('listitem').filter({ hasText: 'Audit partial payment' }).getByRole('button').click();
    await expect(dialog.getByRole('region', { name: t('bill.linkHistory') })).toContainText(t('bill.detached'));
    await expect(dialog).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  });
}
