#!/usr/bin/env bash
# Supabase CLI 2.109.1 `supabase db dump` pipelines, copied verbatim from the
# CLI's own `--dry-run` output and run inside the synthetic source container.
# Test fixture only: it never contacts a real project. Only the connection
# environment differs from the generated CLI script.
#
#   roles                       --role-only
#   schema                      (no flags: default schema dump)
#   auth-schema                 -s auth
#   supabase-migrations-schema  -s supabase_migrations
#   data                        --data-only --use-copy -x auth.sessions
#                               -x auth.refresh_tokens -x auth.mfa_amr_claims
#                               -x auth.one_time_tokens -x auth.flow_state
#   migration-history           --data-only --use-copy -s supabase_migrations
#   auth-schema-migrations      the drill's one read of auth.schema_migrations
set -euo pipefail

export PGHOST="127.0.0.1"
export PGPORT="5432"
export PGUSER="postgres"
export PGDATABASE="postgres"

readonly schema_dump_excluded='information_schema|pg_*|_analytics|_realtime|_supavisor|auth|etl|extensions|pgbouncer|realtime|storage|supabase_functions|supabase_migrations|cron|dbdev|graphql|graphql_public|net|pgmq|pgsodium|pgsodium_masks|pgtle|repack|tiger|tiger_data|timescaledb_*|_timescaledb_*|topology|vault'
readonly data_dump_excluded='information_schema|pg_*|graphql|graphql_public|pgsodium|pgsodium_masks|pgtle|repack|tiger|tiger_data|timescaledb_*|_timescaledb_*|topology|vault|etl|extensions|pgbouncer|realtime|supabase_migrations|_analytics|_realtime|_supavisor'

dump_roles() {
  pg_dumpall \
      --roles-only \
      --role "postgres" \
      --quote-all-identifier \
      --no-role-passwords \
      --no-comments \
  | sed -E 's/^\\(un)?restrict .*$/-- &/' \
  | sed -E "s/^CREATE ROLE \"(anon|authenticated|authenticator|cli_login_.*|dashboard_user|pgbouncer|postgres|service_role|supabase_.*|pgsodium_keyholder|pgsodium_keyiduser|pgsodium_keymaker|pgtle_admin)\"/-- &/" \
  | sed -E "s/^ALTER ROLE \"(anon|authenticated|authenticator|cli_login_.*|dashboard_user|pgbouncer|postgres|service_role|supabase_.*|pgsodium_keyholder|pgsodium_keyiduser|pgsodium_keymaker|pgtle_admin)\"/-- &/" \
  | sed -E "s/ (NOSUPERUSER|NOREPLICATION)//g" \
  | sed -E "s/^-- (.* SET \"(pgaudit.*|pgrst.*|session_replication_role|statement_timeout|track_io_timing)\" .*)/\1/" \
  | sed -E "s/GRANT \".*\" TO \"(anon|authenticated|authenticator|cli_login_.*|dashboard_user|pgbouncer|postgres|service_role|supabase_.*|pgsodium_keyholder|pgsodium_keyiduser|pgsodium_keymaker|pgtle_admin)\"/-- &/" \
  | sed -E "/^--/d" \
  | uniq

  # Reset session config generated by pg_dump
  echo "RESET ALL;"
}

dump_schema() {
  local excluded="$1"
  shift
  pg_dump \
      --schema-only \
      --quote-all-identifier \
      --role "postgres" \
      --exclude-schema "${excluded}" \
      "$@" \
  | sed -E 's/^\\(un)?restrict .*$/-- &/' \
  | sed -E 's/^CREATE SCHEMA "/CREATE SCHEMA IF NOT EXISTS "/' \
  | sed -E 's/^CREATE TABLE "/CREATE TABLE IF NOT EXISTS "/' \
  | sed -E 's/^CREATE SEQUENCE "/CREATE SEQUENCE IF NOT EXISTS "/' \
  | sed -E 's/^CREATE VIEW "/CREATE OR REPLACE VIEW "/' \
  | sed -E 's/^CREATE FUNCTION "/CREATE OR REPLACE FUNCTION "/' \
  | sed -E 's/^CREATE TRIGGER "/CREATE OR REPLACE TRIGGER "/' \
  | sed -E 's/^CREATE PUBLICATION "supabase_realtime/-- &/' \
  | sed -E 's/^CREATE EVENT TRIGGER /-- &/' \
  | sed -E 's/^         WHEN TAG IN /-- &/' \
  | sed -E 's/^   EXECUTE FUNCTION /-- &/' \
  | sed -E 's/^ALTER EVENT TRIGGER /-- &/' \
  | sed -E 's/^ALTER PUBLICATION "supabase_realtime_/-- &/' \
  | sed -E 's/^ALTER FOREIGN DATA WRAPPER (.+) OWNER TO /-- &/' \
  | sed -E 's/^ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin"/-- &/' \
  | sed -E 's/^GRANT ALL ON FOREIGN DATA WRAPPER (.+) TO "postgres" WITH GRANT OPTION/-- &/' \
  | sed -E "s/^GRANT (.+) ON (.+) \"(${excluded})\"/-- &/" \
  | sed -E "s/^REVOKE (.+) ON (.+) \"(${excluded})\"/-- &/" \
  | sed -E 's/^(CREATE EXTENSION IF NOT EXISTS "pg_tle").+/\1;/' \
  | sed -E 's/^(CREATE EXTENSION IF NOT EXISTS "pgsodium").+/\1;/' \
  | sed -E 's/^(CREATE EXTENSION IF NOT EXISTS "pgmq").+/\1;/' \
  | sed -E 's/^COMMENT ON EXTENSION (.+)/-- &/' \
  | sed -E 's/^CREATE POLICY "cron_job_/-- &/' \
  | sed -E 's/^ALTER TABLE "cron"/-- &/' \
  | sed -E 's/^SET transaction_timeout = 0;/-- &/' \
  | sed -E "/^--/d"
}

dump_data() {
  local excluded="$1"
  shift
  # Disable triggers so that data dump can be restored exactly as it is
  echo "SET session_replication_role = replica;
"
  pg_dump \
      --data-only \
      --quote-all-identifier \
      --role "postgres" \
      --exclude-schema "${excluded}" \
      --exclude-table "auth.schema_migrations" \
      --exclude-table "storage.migrations" \
      --exclude-table "supabase_functions.migrations" \
      "$@" \
  | sed -E 's/^\\(un)?restrict .*$/-- &/'

  # Reset session config generated by pg_dump
  echo "RESET ALL;"
}

case "${1:-}" in
  roles) dump_roles ;;
  schema) dump_schema "${schema_dump_excluded}" ;;
  auth-schema) dump_schema "" --schema=auth ;;
  supabase-migrations-schema) dump_schema "" --schema=supabase_migrations ;;
  data)
    dump_data "${data_dump_excluded}" \
      --schema "*" \
      --exclude-table \"auth\".\"sessions\" --exclude-table \"auth\".\"refresh_tokens\" --exclude-table \"auth\".\"mfa_amr_claims\" --exclude-table \"auth\".\"one_time_tokens\" --exclude-table \"auth\".\"flow_state\"
    ;;
  migration-history) dump_data "" --schema "supabase_migrations" ;;
  auth-schema-migrations)
    psql -X -At -v ON_ERROR_STOP=1 -c 'SELECT version FROM auth.schema_migrations ORDER BY version'
    ;;
  *)
    printf '%s\n' 'usage: cli-2.109.1-dump.sh {roles|schema|auth-schema|supabase-migrations-schema|data|migration-history|auth-schema-migrations}' >&2
    exit 64
    ;;
esac
